-- Creaci�n del secuenciador
create sequence alohandes_sequence;

--Crear tabla PROPIETARIO
CREATE TABLE PROPIETARIO
   (
    NOMBRE VARCHAR2(255 BYTE),
    NUMEROIDENTIFICACION NUMBER,
    TIPOIDENTIFICACION VARCHAR2(255 BYTE),
    TIPOPROPIETARIO VARCHAR2(255 BYTE),
    CONSTRAINT PK_PROPIETARIO PRIMARY KEY(NUMEROIDENTIFICACION,TIPOIDENTIFICACION));
    
ALTER TABLE PROPIETARIO
	ADD CONSTRAINT UN_PROPIETARIO_NUMEROID
	UNIQUE (NUMEROIDENTIFICACION)
ENABLE;

ALTER TABLE PROPIETARIO
ADD CHECK (TIPOPROPIETARIO IN ('PROFESOR', 'EMPLEADO', 'EGRESADO', 'ESTUDIANTE', 'PADRE')) 
ENABLE;

--Crear tabla DOMINIO
CREATE TABLE DOMINIO 
   (
    
    REGISTRO NUMBER,
    TIPOREGISTRO VARCHAR2(255 BYTE),
    NOMBRE VARCHAR2(255 BYTE),
    HORARIO VARCHAR2(255 BYTE),
    UBICACION VARCHAR2(255 BYTE),
    CONSTRAINT PK_HOSTAL PRIMARY KEY(REGISTRO, TIPOREGISTRO));

ALTER TABLE DOMINIO
ADD CHECK (TIPOREGISTRO IN ('HOTEL', 'HOSTAL', 'EMPRESA', 'CC', 'CE', 'PA')) 
ENABLE;
--Crear tabla VECINOS
CREATE TABLE VECINOS
    (
     NOMBRE VARCHAR2(255 BYTE),
     NUMEROIDENTIFICACION NUMBER,
     TIPOIDENTIFICACION VARCHAR2(255 BYTE),
     CONSTRAINT PK_VECINOS PRIMARY KEY(NUMEROIDENTIFICACION,TIPOIDENTIFICACION));
     
ALTER TABLE VECINOS
	ADD CONSTRAINT UN_VECINOS_NUMEROID
	UNIQUE (NUMEROIDENTIFICACION)
ENABLE;

ALTER TABLE VECINOS
ADD CHECK (TIPOIDENTIFICACION IN ( 'CC', 'CE', 'PA')) 
ENABLE;

--Crear tabla CLIENTE
CREATE TABLE CLIENTE
   (
   NOMBRE VARCHAR2(255 BYTE),
   NUMEROIDENTIFICACION NUMBER,
   TIPOIDENTIFICACION VARCHAR2(255 BYTE),
   TIPOCLIENTE  VARCHAR2(255 BYTE),
   CONSTRAINT PK_CLIENTE PRIMARY KEY(NUMEROIDENTIFICACION, TIPOIDENTIFICACION));
     
ALTER TABLE CLIENTE
	ADD CONSTRAINT UN_CLIENTE_NUMEROID 
	UNIQUE (NUMEROIDENTIFICACION)
ENABLE;

ALTER TABLE CLIENTE
ADD CHECK (TIPOCLIENTE IN ('PROFESOR', 'EMPLEADO', 'EGRESADO', 'ESTUDIANTE', 'PADRE')) 
ENABLE;

ALTER TABLE CLIENTE
ADD CHECK (TIPOIDENTIFICACION IN ( 'TI', 'CC', 'CE', 'PA')) 
ENABLE;
--Crear tabla APARTAMENTO
CREATE TABLE APARTAMENTO
   (
    NUMEROHABITACIONES NUMBER,
    SERVICIOS VARCHAR2(255 BYTE),
    UBICACION VARCHAR2(255 BYTE),
    IDPROPIETARIO NUMBER,
    TIPOIDENTIFICACION VARCHAR2(255 BYTE),
    CONSTRAINT PK_APARTAMENTO PRIMARY KEY(UBICACION));
    
ALTER TABLE APARTAMENTO
   ADD CONSTRAINT fk_a_propietario
   FOREIGN KEY (IDPROPIETARIO,TIPOIDENTIFICACION)
   REFERENCES propietario(NUMEROIDENTIFICACION,TIPOIDENTIFICACION)
ENABLE;

--Crear tabla VIVIENDA
CREATE TABLE VIVIENDA
   (
   CARACTERISTICASSEGURO VARCHAR2(255 BYTE),
   MENAJE VARCHAR2(255 BYTE),
   NUMERODIASUSADA NUMBER,
   NUMEROHABITACIONES NUMBER,
   SERVICIOS VARCHAR2(255 BYTE),
   UBICACION VARCHAR2(255 BYTE),
   IDVECINO NUMBER,
   TIPOIDENTIFICACION VARCHAR2(255 BYTE),
   CONSTRAINT VIVIENDA_PK PRIMARY KEY(UBICACION));
   
ALTER TABLE VIVIENDA
   ADD CONSTRAINT fk_v_vecino
   FOREIGN KEY (idvecino, TIPOIDENTIFICACION)
   REFERENCES vecinos(NUMEROIDENTIFICACION,TIPOIDENTIFICACION)
ENABLE;

ALTER TABLE VIVIENDA
ADD CONSTRAINT CK_V_NUMERODIASUSADA
	CHECK (numerodiasusada < 30)
ENABLE;

ALTER TABLE VIVIENDA
ADD CONSTRAINT CK_V_NUMEROHABITACIONES
	CHECK (numerohabitaciones > 1)
ENABLE;

--Crear tabla HABITACION
CREATE TABLE HABITACION
   (
    ID NUMBER,
    CAPACIDAD NUMBER,
    COMPARTIDACONCUANTOS NUMBER,
    DIASUSADA NUMBER,
    NUMEROESTRELLAS NUMBER,
    NUMEROHAB NUMBER,
    PRECIO NUMBER,
    SERVICIOS VARCHAR2(255 BYTE),
    TAMANO VARCHAR2(255 BYTE),
    CATEGORIA VARCHAR2(30 BYTE),
    IDDOMINIO NUMBER,
    TIPOREGDOMINIO VARCHAR2(30 BYTE),
    CONSTRAINT PK_HABITACION PRIMARY KEY(ID)
    );
    
ALTER TABLE HABITACION
   ADD CONSTRAINT FK_HAB_DOM
   FOREIGN KEY (IDDOMINIO,TIPOREGDOMINIO)
   REFERENCES DOMINIO(REGISTRO, TIPOREGISTRO)
ENABLE;

ALTER TABLE HABITACION
ADD CONSTRAINT CK_HAB_CAPACIDAD
	CHECK (CAPACIDAD > 0)
ENABLE;

ALTER TABLE HABITACION
ADD CONSTRAINT CK_HAB_COMPARTIDA
	CHECK (COMPARTIDACONCUANTOS >= 0)
ENABLE;

ALTER TABLE HABITACION
ADD CONSTRAINT CK_HAB_DIAS
	CHECK (DIASUSADA >= 0)
ENABLE;

ALTER TABLE HABITACION
ADD CONSTRAINT CK_HAB_NUMESTRELLAS
	CHECK (NUMEROESTRELLAS >= 0)
ENABLE;

ALTER TABLE HABITACION
ADD CONSTRAINT CK_HAB_PRECIO
	CHECK (PRECIO >= 0)
ENABLE;

--CREAR OFERTA
CREATE TABLE OFERTA
   (
    ID NUMBER,
    DESCUENTO NUMBER,
    DIASACTIVA NUMBER,
    DIASUSADA NUMBER,
    FECHAFIN DATE,
    FECHAINICIO DATE,
    TIEMPOCONTRATO VARCHAR2(255 BYTE),
    CONSTRAINT PK_OFERTA PRIMARY KEY(ID)
    );

ALTER TABLE OFERTA
ADD CONSTRAINT CK_OFE_DESCUENTO
	CHECK (DESCUENTO <= 100)
ENABLE;

ALTER TABLE OFERTA
ADD CONSTRAINT CK_OFE_DIASACT
	CHECK ( DIASACTIVA>= 0)
ENABLE;

--CREAR RESERVA
CREATE TABLE RESERVA
   (
    ID NUMBER,
    COSTOPAGADO NUMBER,
    COSTOTOTAL NUMBER,
    FECHAIDA DATE,
    FECHALLEGADA DATE,
    FECHADEPAGO DATE,
    TIEMPOALOJAMIENTO VARCHAR2(255 BYTE),
    IDCLIENTE NUMBER,
    TIPOIDCLIENTE VARCHAR2(255 BYTE),
    IDOFERTA NUMBER,
    CONSTRAINT PK_RESERVA PRIMARY KEY(ID)
    );
    
ALTER TABLE RESERVA
   ADD CONSTRAINT FK_RES_CLI
   FOREIGN KEY (IDCLIENTE,TIPOIDCLIENTE)
   REFERENCES CLIENTE(NUMEROIDENTIFICACION, TIPOIDENTIFICACION)
ENABLE;
    
    
ALTER TABLE RESERVA
   ADD CONSTRAINT FK_RES_OFE
   FOREIGN KEY (IDOFERTA)
   REFERENCES OFERTA(ID)
ENABLE;

--CREAR SERVICIOSADICIONALES
CREATE TABLE SERVICIOSADICIONALES
   (
    ID NUMBER,
    COSTO NUMBER,
    NOMBRE VARCHAR2(255 BYTE),
    IDOFERTA NUMBER
    );
    
ALTER TABLE SERVICIOSADICIONALES
   ADD CONSTRAINT FK_SERVADI_OFERTA
   FOREIGN KEY (IDOFERTA)
   REFERENCES OFERTA(ID)
ENABLE;

ALTER TABLE SERVICIOSADICIONALES
    ADD CONSTRAINT CK_SERVADI_COSTO
	CHECK (COSTO > 0)
ENABLE;

-- CREAR LA TABLA QUE UNE LA OFERTA Y LA HABITACION
CREATE TABLE OFERTAHABITACION
(   
    IDOFERTA NUMBER,
    IDHABITACION NUMBER,
    CONSTRAINT PK_OFERTAHABITACION PRIMARY KEY(IDOFERTA,IDHABITACION)
    );
    
ALTER TABLE OFERTAHABITACION
   ADD CONSTRAINT FK_OFERTAHABITACION_HAB
   FOREIGN KEY (IDHABITACION)
   REFERENCES HABITACION(ID)
ENABLE;

ALTER TABLE OFERTAHABITACION
   ADD CONSTRAINT FK_OFERTAHABITACION_OFE
   FOREIGN KEY (IDOFERTA)
   REFERENCES OFERTA(ID)
ENABLE;


-- CREAR LA TABLA QUE UNE LA OFERTA Y LA VIVIENDA
CREATE TABLE OFERTAVIVIENDA
(   
    IDOFERTA NUMBER,
    IDVIVIENDA  VARCHAR2(255 BYTE),
    CONSTRAINT PK_OFERTAVIVIENDA PRIMARY KEY(IDOFERTA,IDVIVIENDA)
    );
    
ALTER TABLE OFERTAVIVIENDA
   ADD CONSTRAINT FK_OFERTAVIVIENDA_VIV
   FOREIGN KEY (IDVIVIENDA)
   REFERENCES VIVIENDA(UBICACION)
ENABLE;

ALTER TABLE OFERTAVIVIENDA
   ADD CONSTRAINT FK_OFERTAVIVIENDA_OFE
   FOREIGN KEY (IDOFERTA)
   REFERENCES OFERTA(ID)
ENABLE;


-- CREAR LA TABLA QUE UNE LA OFERTA Y EL APARTAMENTO
CREATE TABLE OFERTAAPARTAMENTO
(   
    IDOFERTA NUMBER,
    IDAPARTAMENTO  VARCHAR2(255 BYTE),
    CONSTRAINT PK_OFERTAAPARTAMENTO PRIMARY KEY(IDOFERTA,IDAPARTAMENTO)
    );
    
ALTER TABLE OFERTAAPARTAMENTO
   ADD CONSTRAINT FK_OFERTAAPARTAMENTO_APA
   FOREIGN KEY (IDAPARTAMENTO)
   REFERENCES APARTAMENTO(UBICACION)
ENABLE;

ALTER TABLE OFERTAAPARTAMENTO
   ADD CONSTRAINT FK_OFERTAAPARTAMENTO_OFE
   FOREIGN KEY (IDOFERTA)
   REFERENCES OFERTA(ID)
ENABLE;

CREATE TABLE RESERVACOLECTIVA
(ID NUMBER,
TIPOIDCLIENTE VARCHAR2(255 BYTE),
IDCLIENTE NUMBER,
FECHALLEGADA DATE,
FECHAIDA DATE,
FECHADEPAGO DATE,
CANTIDAD NUMBER,
TIPOALOJAMIENTO VARCHAR2(255 BYTE),
COSTO NUMBER,
CONSTRAINT PK_RESERVACOLECTIVA PRIMARY KEY(ID)
);

ALTER TABLE RESERVACOLECTIVA
ADD CONSTRAINT FK_RESCOL_CLI
FOREIGN KEY (IDCLIENTE, TIPOIDCLIENTE)
REFERENCES CLIENTE (NUMEROIDENTIFICACION, TIPOIDENTIFICACION)
ENABLE;

ALTER TABLE RESERVACOLECTIVA
ADD CHECK (TIPOALOJAMIENTO IN ('APARTAMENTO', 'VIVIENDA', 'HABITACION'))
ENABLE;

-- CREAR LA TABLA QUE UNE LA RESERVA CON RESERVA COLECTIVA
CREATE TABLE RESCOLRES
(   
    IDRESERVA NUMBER,
    IDRESERVACOLECTIVA NUMBER,
    CONSTRAINT PK_RESCOLRES PRIMARY KEY(IDRESERVA ,IDRESERVACOLECTIVA )
    );
    
ALTER TABLE RESCOLRES
   ADD CONSTRAINT FK_RESCOLRES_RES
   FOREIGN KEY (IDRESERVA )
   REFERENCES RESERVA(ID)
ENABLE;

ALTER TABLE RESCOLRES
   ADD CONSTRAINT FK_RESCOLRES_RESCOL
   FOREIGN KEY (IDRESERVACOLECTIVA )
   REFERENCES RESERVACOLECTIVA(ID)
ENABLE;

COMMIT;
