-- PRUEBA RF10
-- la base de datos tiene los datos de finalizacion de PRUEBA_RF9

--Crear reserva3 (no debe ser creada)
INSERT INTO RESERVA
(ID, COSTOPAGADO,COSTOTOTAL,FECHAIDA,FECHALLEGADA,FECHADEPAGO,TIEMPOALOJAMIENTO,IDCLIENTE,TIPOIDCLIENTE,IDOFERTA)
VALUES
(12, 100000, 150000, '18-ENE-2020', '11-ENE-2020', '05-ENE-2020', 'UNA SEMANA', 10, 'CC', 10);

DELETE 
FROM RESERVA
WHERE RESERVA.ID=10 AND RESERVA.IDOFERTA IN( SELECT OFERTA.ID
                                               FROM OFERTA
                                               WHERE OFERTA.ACTIVA='0');                                               
UPDATE OFERTA
SET OFERTA.DISPONIBLE= 'N'
WHERE OFERTA.ID= 10 AND OFERTA.ID IN (SELECT RESERVA.IDOFERTA FROM RESERVA);
COMMIT;

--Actualiza oferta1
UPDATE OFERTA
SET oferta.activa='1'
WHERE OFERTA.ID=10;
COMMIT;

--Crear reserva4 (debe ser creada)
INSERT INTO RESERVA
(ID, COSTOPAGADO,COSTOTOTAL,FECHAIDA,FECHALLEGADA,FECHADEPAGO,TIEMPOALOJAMIENTO,IDCLIENTE,TIPOIDCLIENTE,IDOFERTA)
VALUES
(13, 100000, 150000, '18-ENE-2020', '11-ENE-2020', '05-ENE-2020', 'UNA SEMANA', 10, 'CC', 10);

DELETE 
FROM RESERVA
WHERE RESERVA.ID=10 AND RESERVA.IDOFERTA IN( SELECT OFERTA.ID
                                               FROM OFERTA
                                               WHERE OFERTA.ACTIVA='0');                                               
UPDATE OFERTA
SET OFERTA.DISPONIBLE= 'N'
WHERE OFERTA.ID= 10 AND OFERTA.ID IN (SELECT RESERVA.IDOFERTA FROM RESERVA);
COMMIT;
