INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CARLOS S�NCHEZ', 311, 'CC', 'PROFESOR');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('LAURA MAR�A VARGAS', 321, 'CC', 'EMPLEADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('DANIELA PARRA', 331, 'CC', 'EGRESADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CRISTANCHO', 341, 'CC', 'ESTUDIANTE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN P�REZ', 351, 'CC', 'PADRE');

COMMIT;