INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CARLOS S�NCHEZ', 305, 'CC', 'PROFESOR');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('LAURA MAR�A VARGAS', 310, 'CC', 'EMPLEADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('DANIELA PARRA', 315, 'CC', 'EGRESADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CRISTANCHO', 320, 'CC', 'ESTUDIANTE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN P�REZ', 325, 'CC', 'PADRE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUANA P�REZ', 330, 'CC', 'PROFESOR');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('CLAUDA P�REZ', 335, 'CC', 'EMPLEADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN RODRIGUEZ', 340, 'CC', 'EGRESADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('SOFIA ABADIA', 345, 'CC', 'ESTUDIANTE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('SOFI ABADIA', 350, 'CC', 'PADRE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('FELIPE PARRA', 355, 'CC', 'PROFESOR');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('ADRIANA GARCIA', 360, 'CC', 'EMPLEADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('MAURICIO ORTIZ', 365, 'CC', 'EGRESADO');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('ROBERTO UMANA', 370, 'CC', 'ESTUDIANTE');

INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('BEATRIZ GOMEZ', 375, 'CC', 'PADRE');

COMMIT;