SELECT * 
FROM OFERTAAPARTAMENTO OFAP, OFERTA OFE, APARTAMENTO AP
WHERE OFAP.IDOFERTA = OFE.ID
AND OFAP.IDAPARTAMENTO = AP.UBICACION 
AND AP.SERVICIOS = 'AGUA';

SELECT * 
FROM OFERTAHABITACION OFHA, OFERTA OFE, HABITACION HA
WHERE OFHA.IDOFERTA = OFE.ID
AND OFHA.IDHABITACION = HA.ID 
AND HA.SERVICIOS = 'AGUA';

SELECT * 
FROM OFERTAVIVIENDA OFVI, OFERTA OFE, VIVIENDA VI
WHERE OFVI.IDOFERTA = OFE.ID
AND OFVI.IDVIVIENDA = VI.UBICACION 
AND VI.SERVICIOS = 'AGUA';
---

--INICIALIZACION
--oferta proveedor PROPIETARIO

INSERT INTO PROPIETARIO
(NOMBRE, NUMEROIDENTIFICACION, TIPOIDENTIFICACION, TIPOPROPIETARIO)
VALUES
('ALEJANDRO CORTEZ', 141, 'CC', 'EMPLEADO');

-- apto & oferta 1
INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 2 APTO 2903', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(262, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(262, 'CRA 3 # 21-46 TORRE 2 APTO 2903');

-- apto & oferta 2
INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 2 APTO 2906', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(943, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(943, 'CRA 3 # 21-46 TORRE 2 APTO 2906');

INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 1 APTO 0316', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(836, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(836, 'CRA 3 # 21-46 TORRE 1 APTO 0316');



INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CARLOS S?NCHEZ', 311, 'CC', 'PROFESOR');

COMMIT;

INSERT INTO RESERVACOLECTIVA
(id, TIPOIDCLIENTE, IDCLIENTE, FECHALLEGADA, FECHAIDA, FECHADEPAGO, CANTIDAD, TIPOALOJAMIENTO, COSTO)
values 
(1231, 'CC', 311, '22-MAR-20', '23-MAR-20', '23-MAR-20', 1, 'APARTAMENTO', 1232);

INSERT INTO RESERVACOLECTIVA
(ID, TIPOIDCLIENTE, IDCLIENTE, FECHALLEGADA, FECHAIDA, FECHADEPAGO, CANTIDAD, TIPOALOJAMIENTO, COSTO)
VALUES
(1234567, 'CC', 311, '20-MAR-20', '20-MAR-20', '20-MAR-20', 1, 'VIVIENDA', 10000 );

INSERT INTO RESERVA
(ID, COSTOPAGADO, COSTOTOTAL, FECHAIDA, FECHALLEGADA, FECHADEPAGO, TIEMPOALOJAMIENTO, IDCLIENTE , TIPOIDCLIENTE, IDOFERTA)
VALUES
(1123456, 10000, 11000, '20-MAR-20', '20-MAR-20', '20-MAR-20', 'dias', 311, 10000 );


INSERT INTO RESCOLRES (IDRESERVA, IDRESERVACOLECTIVA) values (1123456, 1234567);

--2020-04-12 11:03:04
