-- sentencias de consulta
SELECT * 
FROM OFERTAAPARTAMENTO OFAP, OFERTA OFE, APARTAMENTO AP
WHERE OFAP.IDOFERTA = OFE.ID
AND OFAP.IDAPARTAMENTO = AP.UBICACION 
AND AP.SERVICIOS = 'AGUA';

SELECT * 
FROM OFERTAHABITACION OFHA, OFERTA OFE, HABITACION HA
WHERE OFHA.IDOFERTA = OFE.ID
AND OFHA.IDHABITACION = HA.ID 
AND HA.SERVICIOS = 'AGUA';

SELECT * 
FROM OFERTAVIVIENDA OFVI, OFERTA OFE, VIVIENDA VI
WHERE OFVI.IDOFERTA = OFE.ID
AND OFVI.IDVIVIENDA = VI.UBICACION 
AND VI.SERVICIOS = 'AGUA';
---

--setteo para pruebas con APARTAMENTO AGUA

INSERT INTO PROPIETARIO
(NOMBRE, NUMEROIDENTIFICACION, TIPOIDENTIFICACION, TIPOPROPIETARIO)
VALUES
('ALEJANDRO CORTEZ', 141, 'CC', 'EMPLEADO');

-- apto & oferta 1
INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 2 APTO 2903', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(262, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(262, 'CRA 3 # 21-46 TORRE 2 APTO 2903');

-- apto & oferta 2
INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 2 APTO 2906', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(31019, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(31019, 'CRA 3 # 21-46 TORRE 2 APTO 2906');

-- apto & oferta 3
INSERT INTO APARTAMENTO
(NUMEROHABITACIONES, SERVICIOS,UBICACION,IDPROPIETARIO,TIPOIDENTIFICACION)
VALUES
(2, 'AGUA', 'CRA 3 # 21-46 TORRE 1 APTO 0316', 141, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(31022, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAAPARTAMENTO
(IDOFERTA, IDAPARTAMENTO)
VALUES
(31022, 'CRA 3 # 21-46 TORRE 1 APTO 0316');


INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CARLOS S?NCHEZ', 311, 'CC', 'PROFESOR');

COMMIT;

--setteo para pruebas con VIVIENDA LUZ

INSERT INTO VECINOS
(NOMBRE, NUMEROIDENTIFICACION, TIPOIDENTIFICACION)
VALUES
('ALAN MARTINEZ', 31152, 'CC');

-- VIVIENDA & oferta 1
INSERT INTO VIVIENDA
(CARACTERISTICASSEGURO, MENAJE,NUMERODIASUSADA,NUMEROHABITACIONES,SERVICIOS,UBICACION,IDVECINO,TIPOIDENTIFICACION)
VALUES
('todo riesgo', '1-Closet, 2-cama, 3-sofa', 1, 2, 'LUZ','CRA 4 # 231-46 TORRE 4 APTO 203', 31152, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(31157, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAVIVIENDA
(IDOFERTA, IDVIVIENDA)
VALUES
(31157, 'CRA 4 # 231-46 TORRE 4 APTO 203');

-- VIVIENDA & oferta 2
INSERT INTO VIVIENDA
(CARACTERISTICASSEGURO, MENAJE,NUMERODIASUSADA,NUMEROHABITACIONES,SERVICIOS,UBICACION,IDVECINO,TIPOIDENTIFICACION)
VALUES
('contra incendios', '1-Closet, 2-cama, 3-sofa', 1, 2, 'LUZ','CRA 8 # 231-46 TORRE 4 APTO 203', 31152, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(31202, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAVIVIENDA
(IDOFERTA, IDVIVIENDA)
VALUES
(31202, 'CRA 8 # 231-46 TORRE 4 APTO 203');

-- VIVIENDA & oferta 3
INSERT INTO VIVIENDA
(CARACTERISTICASSEGURO, MENAJE,NUMERODIASUSADA,NUMEROHABITACIONES,SERVICIOS,UBICACION,IDVECINO,TIPOIDENTIFICACION)
VALUES
('contra inundaciones', '1-Closet, 2-cama, 3-sofa', 1, 2, 'LUZ, AGUA','CRA 70 # 321-46 TORRE 12 APTO 203', 31152, 'CC');

INSERT INTO OFERTA
(ID, DESCUENTO,DIASACTIVA,DIASUSADA,FECHAFIN,FECHAINICIO,TIEMPOCONTRATO)
VALUES
(31205, 0, 0,0, '20-MAR-2020', '19-MAR-2020', 'UNA SEMANA');

INSERT INTO OFERTAVIVIENDA
(IDOFERTA, IDVIVIENDA)
VALUES
(31205, 'CRA 70 # 321-46 TORRE 12 APTO 203');


INSERT INTO CLIENTE
(NOMBRE, NUMEROIDENTIFICACION,TIPOIDENTIFICACION,TIPOCLIENTE)
VALUES
('JUAN CARLOS S?NCHEZ', 31206, 'CC', 'PROFESOR');

COMMIT;



--2020-04-12 11:03:04
