-- CONSULTAR EL NUMERO DE DIAS PARA OFERTAS
create index indNumSem on Oferta(numeroSemana);

SELECT SEL1.NUMEROSEMANA, SEL1.TOTALDIASUSADA, OFE2.ID,OFE2.DESCUENTO,OFE2.DIASACTIVA
,OFE2.FECHAFIN,OFE2.FECHAINICIO,OFE2.TIEMPOCONTRATO,OFE2.ACTIVA,OFE2.DISPONIBLE
FROM 
(SELECT OFE.ID, OFE.NUMEROSEMANA,SUM(OFE.DIASUSADA) AS TOTALDIASUSADA
FROM OFERTA OFE, RESERVA RES
WHERE OFE.ID = RES.IDOFERTA
GROUP BY OFE.ID, OFE.NUMEROSEMANA
) SEL1,
OFERTA OFE2
WHERE SEL1.ID = OFE2.ID
ORDER BY SEL1.NUMEROSEMANA DESC, SEL1.TOTALDIASUSADA DESC
;

-- CONSULTAR EL NUMERO DE SOLICITUDES PARA OPERADORES
SELECT SEL2.NUMEROSEMANA, SEL2.NUMSOLICITUDES, DOM2.REGISTRO, DOM2.TIPOREGISTRO, DOM2.NOMBRE, DOM2.HORARIO, DOM2.UBICACION
FROM(
    SELECT DOM.REGISTRO, DOM.TIPOREGISTRO, OFER.NUMEROSEMANA, COUNT(DOM.REGISTRO) AS NUMSOLICITUDES
    FROM DOMINIO DOM, HABITACION HAB, OFERTAHABITACION OFEHAB, OFERTA OFER, RESERVA RES
    WHERE DOM.REGISTRO = HAB.IDDOMINIO
    AND DOM.TIPOREGISTRO = HAB.TIPOREGDOMINIO
    AND HAB.ID = OFEHAB.IDHABITACION
    AND OFEHAB.IDOFERTA = OFER.ID
    AND OFER.ID = RES.IDOFERTA
    GROUP BY DOM.REGISTRO, DOM.TIPOREGISTRO, OFER.NUMEROSEMANA) SEL2,
    DOMINIO DOM2
WHERE SEL2.REGISTRO = DOM2.REGISTRO
AND SEL2.TIPOREGISTRO = DOM2.REGISTRO
ORDER BY SEL2.NUMEROSEMANA, SEL2.NUMSOLICITUDES
;

commit;
