-- SELECCIONAR LOS DE ALMENOS UNA VEZ POR MES
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE, COUNT (DISTINCT EXTRACT(MONTH FROM FECHALLEGADA)) NUMRESERVASDISTINTOSMESES,  0 AS TOTALCOST, 0 AS TOTALRES
FROM RESERVA RES
GROUP BY IDCLIENTE,TIPOIDCLIENTE, EXTRACT (YEAR FROM FECHALLEGADA)
HAVING COUNT(DISTINCT EXTRACT(MONTH FROM FECHALLEGADA)) >12
UNION
--SELECCIONAR LOS DE MÁS DE 150
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE, 0, SUM(RES.COSTOTOTAL) AS TOTALPAGADO,  0
FROM RESERVA RES 
WHERE COSTOTOTAL > 150
GROUP BY IDCLIENTE,TIPOIDCLIENTE
UNION
--SELECCIONAR SELECCIONAR LOS DE SUITE
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE, 0, 0, COUNT(DISTINCT RES.ID) AS TOTALRESERVAS
FROM RESERVA RES, OFERTAHABITACION OFHA, HABITACION HAB
WHERE RES.IDOFERTA = OFHA.IDOFERTA
AND OFHA.IDHABITACION = HAB.ID
AND HAB.CATEGORIA = 'SUIT'
GROUP BY IDCLIENTE,TIPOIDCLIENTE;
