

SELECT CLI.NUMEROIDENTIFICACION, CLI.TIPOIDENTIFICACION, CLI.NOMBRE, CLI.TIPOCLIENTE,SEL1.NUMRESERVASDISTINTOSMESES, SEL1.TOTALCOST, SEL1.TOTALRES
FROM(-- SELECCIONAR LOS DE ALMENOS UNA VEZ POR MES
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE,
TO_CHAR(COUNT (DISTINCT EXTRACT(MONTH FROM FECHALLEGADA))) NUMRESERVASDISTINTOSMESES,  'no aplica' AS TOTALCOST, 'no aplica' AS TOTALRES
FROM RESERVA RES
GROUP BY IDCLIENTE,TIPOIDCLIENTE, EXTRACT (YEAR FROM FECHALLEGADA)
HAVING COUNT(DISTINCT EXTRACT(MONTH FROM FECHALLEGADA)) >12
UNION
--SELECCIONAR LOS DE MÁS DE 150
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE, 'no aplica', TO_CHAR(SUM(RES.COSTOTOTAL)) AS TOTALPAGADO,  'no aplica'
FROM RESERVA RES 
WHERE COSTOTOTAL > 150
GROUP BY IDCLIENTE,TIPOIDCLIENTE
UNION
--SELECCIONAR SELECCIONAR LOS DE SUITE
SELECT RES.IDCLIENTE, RES.TIPOIDCLIENTE, 'no aplica', 'no aplica', TO_CHAR(COUNT(DISTINCT RES.ID)) AS TOTALRESERVAS
FROM RESERVA RES, OFERTAHABITACION OFHA, HABITACION HAB
WHERE RES.IDOFERTA = OFHA.IDOFERTA
AND OFHA.IDHABITACION = HAB.ID
AND HAB.CATEGORIA = 'SUIT'
GROUP BY IDCLIENTE,TIPOIDCLIENTE) SEL1, CLIENTE CLI
WHERE SEL1.IDCLIENTE = CLI.NUMEROIDENTIFICACION
AND SEL1.TIPOIDCLIENTE = CLI.TIPOIDENTIFICACION;

commit;
