SELECT * 
FROM(
    SELECT * 
    FROM OFERTA OFE
        INNER JOIN
        OFERTAHABITACION OFEHAB
        ON OFE.ID = OFEHAB.IDOFERTA
        INNER JOIN
        OFERTAAPARTAMENTO OFEAPA
        ON OFE.ID = OFEAPA.IDOFERTA
        INNER JOIN
        OFERTAVIVIENDA OFEVIV
        ON OFE.ID = OFEVIV.IDOFERTA
        INNER JOIN 
        (
        SELECT OFE.ID, COUNT(RES.ID) AS VECESCOMPRADA
        FROM RESERVA RES, OFERTA OFE
        WHERE OFE.ID = RES.IDOFERTA
        GROUP BY OFE.ID
        )SEL1 
        ON SEL1.ID = OFE.ID
    ORDER BY SEL1.VECESCOMPRADA
    )
WHERE ROWNUM >20
;